# show grants for admin;

DROP USER IF EXISTS appuser;
CREATE USER appuser;

GRANT
    SELECT, INSERT, UPDATE, DELETE,
    CREATE, DROP, RELOAD, PROCESS, REFERENCES, INDEX, ALTER,
    SHOW DATABASES, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE,
    REPLICATION SLAVE, REPLICATION CLIENT, CREATE VIEW, SHOW VIEW,
    CREATE ROUTINE, ALTER ROUTINE, CREATE USER, EVENT, TRIGGER
ON *.* TO `appuser`@`%` WITH GRANT OPTION;
