# https://zenn.dev/jrsyo/articles/e42de409e62f5d

FROM node:24.14.0-slim AS node
FROM ubuntu:24.04 AS base

# apt clean && rm -rf /var/lib/apt/lists/*

# new way to get node, let's copy in the specific version we want from a docker image
# this avoids depdency package installs (python3) that the deb package requires
COPY --from=node /usr/local/include/ /usr/local/include/
COPY --from=node /usr/local/lib/ /usr/local/lib/
COPY --from=node /usr/local/bin/ /usr/local/bin/

# DEBIAN_FRONTEND=noninteractive は、tzdata のインストール時の
# 地域選択のインタラクティブなプロンプトを抑制するためのもの
ENV DEBIAN_FRONTEND=noninteractive

RUN groupadd --gid 2000 appuser \
    && useradd --uid 2000 --gid appuser --shell /bin/bash --home-dir /app --create-home appuser

RUN apt-get update && apt-get upgrade -y

# ssh server の設定

RUN apt-get update && apt-get install -y --no-install-recommends \
        openssh-server \
    && mkdir -p /var/run/sshd \
    && ssh-keygen -A \
    && sed -i 's/^AcceptEnv.*$/AcceptEnv LC_* GIT_AUTHOR_* GIT_COMMITTER_*/' /etc/ssh/sshd_config \
    && sed -i 's/^#AllowAgentForwarding.*$/AllowAgentForwarding yes/' /etc/ssh/sshd_config

RUN apt-get update && apt-get install -y \
        wget \
        gnupg \
        ca-certificates \
        software-properties-common \
    && wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor > /usr/share/keyrings/hashicorp-archive-keyring.gpg \
    && echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" > /etc/apt/sources.list.d/hashicorp.list \
    && wget -O- https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor > /usr/share/keyrings/pgdg-archive-keyring.gpg \
    && echo "deb [signed-by=/usr/share/keyrings/pgdg-archive-keyring.gpg] https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list \
    && apt-get update

RUN apt-get update && apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        gnupg \
        lsb-release \
        \
        tini \
        locales \
        tzdata \
        postgresql-client-17 \
        \
        language-pack-ja-base language-pack-ja  \
        screen \
        telnet \
        sudo \
        vim \
        git \
        ssh \
        curl \
        psmisc \
        dnsutils \
        iputils-ping \
        less \
        jq \
        apache2-utils \
        unzip \
        zip \
        groff \
        direnv \
        expect \
        \
        terraform

# AWS CLI のインストール

RUN apt-get update && \
    curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    rm -rf aws awscliv2.zip

# その他の設定
RUN npm install -g pm2 pnpm@10.7.1 \
    && mkdir -p /data/pnpm-store \
    && chown -R appuser:appuser /data \
    && pnpm config set script-shell /bin/bash

ENV TZ=Asia/Tokyo
ENV LANG=ja_JP.UTF-8
ENV LC_MESSAGES=C
ENV LC_TIME=C

ENV PNPM_STORE_PATH=/data/pnpm-store

COPY --chown=appuser:appuser build/app /app/
COPY --chown=appuser:appuser build/app/docker/home-appuser-dev/ /app/
RUN chmod 700 /app/.ssh && chmod 600 /app/.ssh/* || true

# pnpm install
USER appuser
RUN cd /app/frontend && pnpm install && \
    cd /app/backend && pnpm install && pnpm db:generate
USER root

EXPOSE 8080
EXPOSE 8800
EXPOSE 22

ENTRYPOINT ["tini", "--", "bash", "/app/etc/onstart-prod-util.sh"]
